version: '3.8'

networks:
  kafka-net:
    external: true
    name: kafka-network
  microservices-net:
    external: true

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb_container
    restart: unless-stopped
    environment:
      - POSTGRES_DB=healthdata
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - kafka-net
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d healthdata"]
      interval: 5s
      retries: 5
      timeout: 2s
      start_period: 5s

  data-processing-service:
    container_name: data-processing-service
    build: .
    ports:
      - "8083:8083"
    networks:
      - kafka-net
      - microservices-net
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: topic
      KAFKA_GROUP: group
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/healthdata
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  timescaledb_data:
