version: '3.8'

networks:
  kafka-net:
    external: true
    name: kafka-network

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=healthdata
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - kafka-net
  app-consumer:
    container_name: al-app
    build: .
    ports:
      - "8083:8083"
    networks:
      - kafka-net
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: topic
      KAFKA_GROUP: group
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/healthdata
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  timescaledb_data: