version: "3.9"

services:
  patient-management-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      USER_SERVICE_URL: http://user-service:8080
      PROCESS_DATA_SERVICE_URL: http://data-processing-service:8083
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true

volumes:
  patient-management-db-data:
